
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 23 20:39:18 ECT 2022
//----------------------------------------------------

package syntactic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMICOLON = 7;
  public static final int DATA_TYPE = 14;
  public static final int PRODUCT = 17;
  public static final int EQUAL = 10;
  public static final int QUOTES = 15;
  public static final int DIVISION = 18;
  public static final int IDENTIFIER = 8;
  public static final int ERROR = 19;
  public static final int OPENING_BRACKETS = 3;
  public static final int STRING = 13;
  public static final int EOF = 0;
  public static final int NUMBER = 9;
  public static final int ADD = 11;
  public static final int MINUS = 16;
  public static final int error = 1;
  public static final int CLOSING_BRACKETS = 4;
  public static final int CLOSING_KEYS = 6;
  public static final int INTEGER = 12;
  public static final int VOID = 2;
  public static final int OPENING_KEYS = 5;
}

